/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nazar Romanenko (https://sketchfab.com/Nazar_Romanenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/csgo-bomb-xyz-homework-detailing-0c230c632e804e14a309b7e9d64878fa
Title: CSGO bomb (XYZ Homework) detailing
*/

import { useGLTF } from "@react-three/drei";

export function Bomb(props) {
  const { nodes, materials } = useGLTF(
    "/models/bomb/csgo_bomb_xyz_homework_detailing.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Plane001_Material006_0.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Plane001_Material009_0.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cube003_Material020_0.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Cube003_Material005_0.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[-14.265, 113.967, 42.435]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh
          geometry={nodes.Cube010_Material005_0.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube010_Material015_0.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Cube009_Material005_0.geometry}
          material={materials["Material.005"]}
          position={[0.143, 0.424, -1.14]}
        />
        <mesh
          geometry={nodes.Cube012_Material005_0.geometry}
          material={materials["Material.005"]}
          position={[0.143, 0.424, -1.14]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cube029_Material008_0.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cube029_Material007_0.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cube030_Material007_0.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cube030_Material008_0.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cube032_Material008_0.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cube032_Material007_0.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cube033_Material008_0.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cube033_Material007_0.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[50.8, 113.91, 88.086]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={100}
      >
        <mesh
          geometry={nodes.Cube011_Material008_0.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cube011_Material007_0.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube_Material001_0.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane_Material003_0.geometry}
        material={materials["Material.003"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube001_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane002_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane003_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube002_Material005_0.geometry}
        material={materials["Material.005"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube004_Material006_0.geometry}
        material={materials["Material.006"]}
        position={[-169.422, 59.575, -85.566]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube005_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Circle_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube006_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube007_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder001_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube008_Material012_0.geometry}
        material={materials["Material.012"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder002_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Circle001_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube015_Material018_0.geometry}
        material={materials["Material.018"]}
        position={[-77.817, 111.112, -19.108]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder003_Material015_0.geometry}
        material={materials["Material.015"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder004_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder005_Material013_0.geometry}
        material={materials["Material.013"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube023_Material015_0.geometry}
        material={materials["Material.015"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder006_Material015_0.geometry}
        material={materials["Material.015"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder007_Material006_0.geometry}
        material={materials["Material.006"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder008_Material013_0.geometry}
        material={materials["Material.013"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder009_Material015_0.geometry}
        material={materials["Material.015"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere_Material019_0.geometry}
        material={materials["Material.019"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCircle_Material016_0.geometry}
        material={materials["Material.016"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube027_Material016_0.geometry}
        material={materials["Material.016"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCircle001_Material016_0.geometry}
        material={materials["Material.016"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube028_Material016_0.geometry}
        material={materials["Material.016"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCurve_Material004_0.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCurve001_Material010_0.geometry}
        material={materials["Material.010"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder010_Material004_0.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCurve003_Material004_0.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder011_Material010_0.geometry}
        material={materials["Material.010"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder012_Material011_0.geometry}
        material={materials["Material.011"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCurve004_Material010_0.geometry}
        material={materials["Material.010"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCurve005_Material011_0.geometry}
        material={materials["Material.011"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube014_Material018_0.geometry}
        material={materials["Material.018"]}
        position={[-60.227, 112.454, 95.128]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube016__0.geometry}
        material={materials["Cube.016__0"]}
        position={[-60.227, 110.035, 95.128]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube017_Material018_0.geometry}
        material={materials["Material.018"]}
        position={[55.164, 111.301, 87.844]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube018_Material018_0.geometry}
        material={materials["Material.018"]}
        position={[77.717, 111.064, -135.287]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube021_Material017_0.geometry}
        material={materials["Material.017"]}
        position={[57.702, 113.836, 24.985]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={12.996}
      />
      <mesh
        geometry={nodes.Cube019_Material017_0.geometry}
        material={materials["Material.017"]}
        position={[57.702, 113.836, -8.927]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={12.996}
      />
      <mesh
        geometry={nodes.Cube013_Material017_0.geometry}
        material={materials["Material.017"]}
        position={[-54.56, 113.788, -22.414]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={12.996}
      />
      <mesh
        geometry={nodes.Cube022_Material017_0.geometry}
        material={materials["Material.017"]}
        position={[-54.56, 113.788, 11.498]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={12.996}
      />
      <mesh
        geometry={nodes.Cylinder014_Material005_0.geometry}
        material={materials["Material.005"]}
        position={[-169.422, 68.177, -128.411]}
        scale={4.397}
      />
      <mesh
        geometry={nodes.Cylinder015_Material005_0.geometry}
        material={materials["Material.005"]}
        position={[-169.422, 52.984, -128.411]}
        scale={4.397}
      />
    </group>
  );
}

useGLTF.preload("/models/bomb/csgo_bomb_xyz_homework_detailing.glb");
